FROM almalinux:9
RUN dnf install -y openssh-server sudo && \
    mkdir /var/run/sshd && \
    useradd -m -s /bin/bash genericuser && \
    echo "genericuser ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers && \
    mkdir -p /home/genericuser/.ssh
COPY files/id_rsa_genericuser.pub /home/genericuser/.ssh/authorized_keys
RUN chown -R genericuser:genericuser /home/genericuser/.ssh && chmod 600 /home/genericuser/.ssh/authorized_keys
RUN ssh-keygen -A

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]

